name: TYPO3 Extension Repository

on: [push]

jobs:
  publish:
    name: Publish new version to TER
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP Version
        run: |
          sudo update-alternatives --set php /usr/bin/php7.4
          php -v

      - name: Update Composer
        run: |
          sudo composer self-update
          composer --version

      - name: Composer Install
        run: |
          composer install

      - name: Create token
        run: |
          rm -f token.txt
          echo "Create token..."
          TYPO3_API_USERNAME=${{ secrets.TYPO3_API_USERNAME }} TYPO3_API_PASSWORD=${{ secrets.TYPO3_API_PASSWORD }} vendor/bin/tailor ter:token:create --name="token for yoast_seo" --extensions=yoast_seo --expires=300 --no-ansi > token.txt
          echo "And wait for token to be active... (60s)"
          sleep 60s

      - name: Get version
        id: get-version
        run: |
          echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Get comment
        id: get-comment
        run: |
          readonly local comment=$(git tag -n10 -l ${{ steps.get-version.outputs.version }} | sed "s/^[0-9.]*[ ]*//g")

          if [[ -z "${comment// }" ]]; then
            echo ::set-output name=comment::Released version ${{ steps.get-version.outputs.version }} of ${{ env.TYPO3_EXTENSION_KEY }}
          else
            echo ::set-output name=comment::$comment
          fi

      - name: Check versions
        run: |
          TYPO3_API_USERNAME=${{ secrets.TYPO3_API_USERNAME }} TYPO3_API_PASSWORD=${{ secrets.TYPO3_API_PASSWORD }} TYPO3_API_TOKEN=$(awk '/Access token:(.*)/ { print $3 }' token.txt) vendor/bin/tailor ter:versions yoast_seo --no-ansi -vvv

      - name: Debug
        run: |
          echo "Version: ${{ steps.get-version.outputs.version }}"
          echo "Comment: ${{ steps.get-comment.outputs.comment }}"